### ISSUE TITLE
Cancelling fractions

### ISSUE THREAD

**Issue by kangwonlee** [kangwonlee/calcul_mental#4]
* On top of a572ba049c28380abcfc2d029b64496c7047bba8
* #2 

## Action Plan

* Generate three integers
    x<sub>0</sub>, x<sub>1</sub>, x<sub>2</sub>, &isin; {x | x &isin; N, 1 < x < 10 }
    x<sub>0</sub> < x<sub>1</sub> < x<sub>2</sub>
* Pick one of {x<sub>0</sub>, x<sub>1</sub>, x<sub>2</sub>} = x<sub>a</sub>
   The others are x<sub>b</sub> < x<sub>c</sub>
* Numerator = x<sub>b</sub> / x<sub>a</sub>
    Denominator = x<sub>c</sub> / x<sub>a</sub>
* Use `fractions` module

## Question

* [x] What if x<sub>b</sub> and x<sub>c</sub> have a common factor? `fractions.gcd(a, b)` [[ref](https://docs.python.org/3.7/library/fractions.html#fractions.gcd)]
* [ ] Number of possible combinations < desirable?
* [ ] Possible to present numerators and denominators as products of prime numbers?
* [ ] How to present fractions on terminals with using default modules only? Or is it better to use `sympy`?
* [x] How to accept an answer? `num / den`? `fractions.Fractions(str)` [[ref](https://docs.python.org/3.7/library/fractions.html#fractions.Fraction)]

**Comment by kangwonlee** [comment]
* 554b6ee235826f99b121aecd2e5f929a179566b8 resolves this issue for now
* Unanswered questions to be separate issues later
